/**
 * generated by Xtext 2.10.0
 */
package xtext;

import xtext.ExpressionStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ExpressionStandaloneSetup extends ExpressionStandaloneSetupGenerated {
  public static void doSetup() {
    new ExpressionStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
