/**
 * generated by Xtext 2.10.0
 */
package xtext;

import xtext.AbstractExpressionRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ExpressionRuntimeModule extends AbstractExpressionRuntimeModule {
}
