/**
 * generated by Xtext 2.10.0
 */
package xtext.expression;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Combo View</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.expression.ExpressionPackage#getComboView()
 * @model
 * @generated
 */
public interface ComboView extends Element
{
} // ComboView
