/**
 * generated by Xtext 2.10.0
 */
package xtext.expression;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Container</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.expression.Container#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see xtext.expression.ExpressionPackage#getContainer()
 * @model
 * @generated
 */
public interface Container extends Element
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link xtext.expression.Element}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see xtext.expression.ExpressionPackage#getContainer_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Element> getElements();

} // Container
