/**
 * generated by Xtext 2.10.0
 */
package xtext.expression;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Label</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.expression.ExpressionPackage#getLabel()
 * @model
 * @generated
 */
public interface Label extends Element
{
} // Label
