/**
 * generated by Xtext 2.10.0
 */
package xtext.expression;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Text View</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.expression.ExpressionPackage#getTextView()
 * @model
 * @generated
 */
public interface TextView extends Element
{
} // TextView
