/**
 * generated by Xtext 2.10.0
 */
package xtext.validation;

import xtext.validation.AbstractExpressionValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ExpressionValidator extends AbstractExpressionValidator {
}
