/*
 * generated by Xtext 2.10.0
 */
package xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import xtext.expression.ui.internal.ExpressionActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ExpressionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ExpressionActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ExpressionActivator.getInstance().getInjector(ExpressionActivator.XTEXT_EXPRESSION);
	}
	
}
