/*
 * generated by Xtext 2.10.0
 */
package xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ExpressionStandaloneSetup extends ExpressionStandaloneSetupGenerated {

	def static void doSetup() {
		new ExpressionStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
