/*
 * generated by Xtext 2.10.0
 */
package xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import xtext.expression.ui.internal.ExpressionActivator;

public class ExpressionUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ExpressionActivator.getInstance().getInjector("xtext.Expression");
	}

}
