/**
 * generated by Xtext 2.10.0
 */
package xtext.expression.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.expression.ComboView;
import xtext.expression.ExpressionPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Combo View</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ComboViewImpl extends ElementImpl implements ComboView
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComboViewImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExpressionPackage.Literals.COMBO_VIEW;
  }

} //ComboViewImpl
