/**
 * generated by Xtext 2.10.0
 */
package xtext.expression.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.expression.ExpressionPackage;
import xtext.expression.Label;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Label</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LabelImpl extends ElementImpl implements Label
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LabelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExpressionPackage.Literals.LABEL;
  }

} //LabelImpl
