/**
 * generated by Xtext 2.10.0
 */
package xtext.expression.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.expression.ExpressionPackage;
import xtext.expression.TextView;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Text View</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TextViewImpl extends ElementImpl implements TextView
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TextViewImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExpressionPackage.Literals.TEXT_VIEW;
  }

} //TextViewImpl
