/**
 * generated by Xtext 2.10.0
 */
package xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import xtext.ui.AbstractExpressionUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ExpressionUiModule extends AbstractExpressionUiModule {
  public ExpressionUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
