/* Generated By:JavaCC: Do not edit this line. AnalizadorLexicoConstants.java */
package Logica;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorLexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ORIENTACION = 6;
  /** RegularExpression Id. */
  int BOLD = 7;
  /** RegularExpression Id. */
  int ITALIC = 8;
  /** RegularExpression Id. */
  int ARIAL = 9;
  /** RegularExpression Id. */
  int TAHOMA = 10;
  /** RegularExpression Id. */
  int PX = 11;
  /** RegularExpression Id. */
  int IS = 12;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 13;
  /** RegularExpression Id. */
  int COMBOBOX = 14;
  /** RegularExpression Id. */
  int CAMPOTEXTO = 15;
  /** RegularExpression Id. */
  int LABEL = 16;
  /** RegularExpression Id. */
  int BOTON = 17;
  /** RegularExpression Id. */
  int PATRON = 18;
  /** RegularExpression Id. */
  int SIMBOLOASIGNACION = 19;
  /** RegularExpression Id. */
  int SEPARADOR = 20;
  /** RegularExpression Id. */
  int ABRIRLLAVE = 21;
  /** RegularExpression Id. */
  int CERRARLLAVE = 22;
  /** RegularExpression Id. */
  int PUNTOYCOMA = 23;
  /** RegularExpression Id. */
  int SIMBOLOMENOR = 24;
  /** RegularExpression Id. */
  int SIMBOLOMAYOR = 25;
  /** RegularExpression Id. */
  int COLOR = 26;
  /** RegularExpression Id. */
  int COLORHEXADECIMAL = 27;
  /** RegularExpression Id. */
  int ESTILOCOLOR = 28;
  /** RegularExpression Id. */
  int ESTILOWIDTH = 29;
  /** RegularExpression Id. */
  int ESTILOHEIGHT = 30;
  /** RegularExpression Id. */
  int ESTILOTIPOFUENTE = 31;
  /** RegularExpression Id. */
  int ESTILOTAMFUENTE = 32;
  /** RegularExpression Id. */
  int ESTILOFUENTE = 33;
  /** RegularExpression Id. */
  int DIGIT = 34;
  /** RegularExpression Id. */
  int NUMERO = 35;
  /** RegularExpression Id. */
  int HIDEBORDER = 36;
  /** RegularExpression Id. */
  int INICIOWIDGET = 37;
  /** RegularExpression Id. */
  int FINWIDGET = 38;
  /** RegularExpression Id. */
  int INICIODECLARACION = 39;
  /** RegularExpression Id. */
  int FINDECLARACION = 40;
  /** RegularExpression Id. */
  int INICIOEXPRESION = 41;
  /** RegularExpression Id. */
  int FINEXPRESION = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<ORIENTACION>",
    "\"bold\"",
    "\"italic\"",
    "\"arial\"",
    "\"tahoma\"",
    "\"px\"",
    "<IS>",
    "<IDENTIFICADOR>",
    "<COMBOBOX>",
    "<CAMPOTEXTO>",
    "<LABEL>",
    "<BOTON>",
    "<PATRON>",
    "\"=\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"<\"",
    "\">\"",
    "<COLOR>",
    "<COLORHEXADECIMAL>",
    "\".color\"",
    "\".width\"",
    "\".height\"",
    "\".fuente\"",
    "\".tamFuente\"",
    "\".estiloFuente\"",
    "<DIGIT>",
    "<NUMERO>",
    "\"\\\'\"",
    "\"wI/\"",
    "\"/wF\"",
    "\"dI/\"",
    "\"/dF\"",
    "\"eI/\"",
    "\"/eF\"",
    "\"[\"",
    "\"]\"",
  };

}
