/*
 * generated by Xtext 2.10.0
 */
package xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import xtext.services.ExpressionGrammarAccess;

@SuppressWarnings("all")
public class ExpressionSyntacticSequencer extends AbstractSyntacticSequencer {

	protected ExpressionGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Container_OrientationParserRuleCall_1_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (ExpressionGrammarAccess) access;
		match_Container_OrientationParserRuleCall_1_q = new TokenAlias(false, true, grammarAccess.getContainerAccess().getOrientationParserRuleCall_1());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getOrientationRule())
			return getOrientationToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * Orientation:
	 * 	"|" | "-";
	 */
	protected String getOrientationToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "|";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Container_OrientationParserRuleCall_1_q.equals(syntax))
				emit_Container_OrientationParserRuleCall_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     Orientation?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID (ambiguity) '[' elements+=Element
	 */
	protected void emit_Container_OrientationParserRuleCall_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
